import { useState, useEffect, useRef} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const inputRef = useRef();
  const [shortUrl, setShortUrl] = useState("");
  

  const handleSubmit = (e:React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const url = inputRef.current.value;
    fetch(`/api/shortUrl` ,{
      method: 'POST',
      headers: {
        'Content-Type':'application/json',
      },
      body: JSON.stringify({url})
    })
     .then( res => res.json())
     .then( data => { console.log(data)});


  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Acortador de Url</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        
      
        <div className={styles.grid}>
          <form  onSubmit={handleSubmit} className={styles.grid}>
           <input ref={inputRef} type="text" className={styles.input} placeholder="Ingresar Url"></input>
           <button  className={styles.button}>Acorta</button>
           <span className={styles.input}></span>
            {shortUrl}:
          </form>
        </div>
     
    </div>
  )
}
